### PR TITLE
Singular artifacts

### LINKED ISSUE #156: versionless artifacts
### Context
Currently all artifacts have version appended to them by default. 

### Feature
add an optional flag for artifacts to be versionless

### PR DESCRIPTION
**Pull request by sshookman**
Resolves #156

### Solution
Added a new field (`singular`) that can be specified at the artifact level to let Skelebot know that this artifact will not be versioned. This will allow the artifact to be pushed and pulled without a version number, meaning there will only ever be a single instance of the artifact available at any given time.

### CODE REVIEW

**Comment by sshookman** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- skelebot/components/repository/artifactoryRepo.py  1
- skelebot/components/repository/s3Repo.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/skelebot/skelebot/pullRequest?prid=6314521&bid=20530615)

**Review by jagmoreira — COMMENTED** [review]
You're missing tests for the push of singular artifacts. Are they not needed?

**Comment by sshookman** [comment]
> You're missing tests for the push of singular artifacts. Are they not needed?

They absolutely are needed. Thanks!

**Comment by sshookman** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- skelebot/components/repository/artifactoryRepo.py  1
- skelebot/components/repository/s3Repo.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/skelebot/skelebot/pullRequest?prid=6314521&bid=20530615)

**Review by jagmoreira — APPROVED** [review]

**Pull request merged**
