### PR TITLE
Cross platform color output

### LINKED ISSUE #73: Terminal colors not working on each environment
In the ERROR message output the as well as the --help output there is some formatted text (color and style). This is done in a manner that does not work on every OS / Terminal Emulator.

The printed text "\u001b[0m\u001b[31mERROR\u001b[0m" may often appear exactly as is, instead of the red "ERROR" label that was intended to display.

The printed text in the --help output to make the name of the project bold "\033[1m{project}\033[0m" is also not safe for every environment.

This code for these can be found in `skelebot/skelebot.py` and `skelebot/common.py` respectively.

In order to support multiple OS and Terminals the colorama package could be used: https://www.geeksforgeeks.org/print-colors-python-terminal/

Test cases will need to be updated in a manner that is also system independent.
This fix should only be a patch version bump.

---

**Acceptance Criteria**
- [x] Terminal Colors are now printed in a system agnostic fashion
- [ ] Test Cases Updated for new Code
- [x] Changelog Updated
- [x] Patch Version Bumped

### PR DESCRIPTION
**Pull request by sgaist**
## What

This pull request refactors the code producing coloured terminal output to use colorama. This should provide a cross-platform uniform output

## Why

Fixes #73

### CODE REVIEW

**Comment by sshookman** [comment]
@sgaist, there have been more merges to master, make sure you update your branch to get the latest changes (should not be conflicting) and please use 1.5.2 for the new version number.

Thanks!

**Comment by sgaist** [comment]
Funny, I just did a pull a few moments ago and it was 1.5.0 :-)

**Comment by sshookman** [comment]
Sorry about that, I had a bugfix that I really wanted to get merged.

**Comment by sgaist** [comment]
No worries, I just found funny that I was updating for 1.5.1 when I saw your message :-) It was a nice coincidence that the timing was so precise.

**Pull request merged**
