### PR TITLE
update python version in base image

### LINKED ISSUE #167: update python in python-base image
### Problem
Current python version 3.6 is not compatible with some latest python packages (e.g. pandas >=1.1.0)

### Solution
Use python 3.8.5-slim image

### PR DESCRIPTION
**Pull request by sherry0531**
Resolves #167 

### Solution
Used python: 3.8.5-slim in base-images/python-base/Dockerfile

### CODE REVIEW

**Comment by jagmoreira** [comment]
I like the idea of updating the base python! However, should we keep a versioned copy of the previous base image in dockerhub?
Updating the base may break some installations (I know a previous version of pyarrow was not providing wheels for python 3.8).

This way we would provide, in Dockerhub:
```
skelebot/python-base:latest (python 3.8)
skelebot/python-base:3.8    (python 3.8, same as latest)
skelebot/python-base:3.6    (python 3.6)
```

Also @sshookman

**Comment by sshookman** [comment]
I think @jagmoreira's right. We should probably start versioning our base images in Docker Hub in order to handle this with breaking existing projects. Should we create another issue for that, or roll it into this one is the question?

**Comment by swangcars** [comment]
I wouldn't mind it at all to try versioning our base images in Docker Hub and roll it into this PR, but I'd need some hand holding as I'm really not that familiar with docker...

**Comment by swangcars** [comment]
Reading [this post](https://stackoverflow.com/questions/56212495/properly-versioning-docker-images), I'm guessing we need to tag images with different versions, use skelebot publish to push both to Docker Hub? Maybe also modify [build function](https://github.com/carsdotcom/skelebot/blob/master/skelebot/systems/execution/docker.py#L54 ) so user can choose which base image to pull and use?

**Comment by jagmoreira** [comment]
@swangcars I think the simplest approach would be to create separate python [Dockerfiles](https://github.com/carsdotcom/skelebot/blob/master/base-images/python-base/Dockerfile), one for each of 3.6, 3.7, 3.8. Then modify the [publish](https://github.com/carsdotcom/skelebot/blob/master/jobs/publish.sh) job to build, tag, and push each one. Something like this:
```
# jobs/publish.sh
...
docker build -t skelebot/python-base:3.6 base-images/python-base/3.6/
docker build -t skelebot/python-base:3.7 base-images/python-base/3.7/
docker build -t skelebot/python-base:3.8 -t skelebot/python-base:latest base-images/python-base/3.8/
docker push --all-tags skelebot/python-base
...
```

That's just an idea for the folder structure. The dockerfiles will be mostly identical expect for the first line (`FROM python:3.x.y-slim`). I guess you could write a bash script to write the Dockerfiles themselves. Me or @sshookman can help with that.

The other thing we need to decide is which version to mark as `latest` as that becomes the default python image for skelebot. If we change from the current one of python 3.6 slim we risk breaking some environments. On the other hand, python 3.6 is scheduled to reach end-of-life on [Dec 2021](https://devguide.python.org/#status-of-python-branches)..

**Comment by sherry0531** [comment]
Closing this. Opening a new PR to resolve this issue: https://github.com/carsdotcom/skelebot/pull/189

**Pull request closed without merging**
